[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd telegram-bot && python bot.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PYTHONPATH = "/app/telegram-bot"
PYTHONUNBUFFERED = "1"

[healthcheck]
enabled = true
path = "/health"
timeout = 30
interval = 60
